core/urls.py
from django.urls import path

from core.views import product, login, basket, checkout, sign_up, logoutUser, \
    BonuseListView,IndexTemplateView


urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('product/', product, name='product'),
    path('login/', login, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('basket/', basket, name='basket'),
    path('checkout/', checkout, name='checkout'),
    path('sign_up/', sign_up, name='sign_up'),
    path('bonuses/', BonuseListView.as_view(), name="bonuses")
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from datetime import datetime
from django.db import models
from django.utils.translation import ugettext_lazy as _



class Category(models.Model):
    title = models.CharField(_('Title'), max_length=40)
    parent_category = models.ForeignKey('self', verbose_name=_('Parent Category'), related_name='sub_categories', on_delete=models.CASCADE, null=True, blank=True)

    # moderations
    order = models.PositiveIntegerField(_('Order'), default=1)
    is_published = models.BooleanField(_('is published'), default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ('order', '-created_at',)

    def __str__(self):
        if self.parent_category:
            return f"{self.id}. {self.title} Parent: {self.parent_category}"
        else:
            return f"{self.id}. {self.title}"


class Product(models.Model):
    title = models.CharField(_('Title'), max_length=40)
    category = models.ForeignKey(Category, verbose_name=_('Category'), related_name='products', on_delete=models.CASCADE)
    code = models.PositiveIntegerField(_('Code'), )
    price = models.DecimalField(_('Price'), max_digits=7, decimal_places=2)
    properties = models.ManyToManyField('PropertyValue', through='ProductProperties', related_name='products')

    # moderations
    order = models.PositiveIntegerField(_('Order'), default=1)
    is_published = models.BooleanField(_('is published'), default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ('order', '-created_at',)

    def __str__(self):
        return self.title
    
    @property
    def main_image(self):
        return self.product_images.all().order_by('is_main').first()
    
    @property
    def discount_price(self):
        today = datetime.now()
        discount_price_obj = self.product_discounts.filter(deadline__gte = today, is_active = True).last()
        if discount_price_obj:
            if discount_price_obj.discount_type == 1 :
                return '%.2f'%(self.price - ((self.price * discount_price_obj.discount_amount)/100))
            return self.price - discount_price_obj.discount_amount    

        return 0


class ProductImage(models.Model):
    image = models.ImageField(_('Image'), upload_to='product_images')
    is_main = models.BooleanField(_('Is main'), default=False)
    product = models.ForeignKey(Product, verbose_name=_('Product'), on_delete=models.CASCADE, related_name='product_images')

    # moderations
    order = models.PositiveIntegerField(_('Order'), default=1)
    is_published = models.BooleanField(_('is published'), default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Product Image')
        verbose_name_plural = _('Product Images')
        ordering = ('order', '-created_at',)

    def __str__(self):
        return self.product.title


class PropertyName(models.Model):
    title = models.CharField(_('Title'), max_length=40)
    SHOW_OPTION_CHOICES = (
        ('select_color', 'Select Color'),
        ('select_text', 'Select text'),
        ('select_option', 'Select option'),
        ('radio_button', 'Radio button'),
    )
    show_option = models.CharField(_('Show option'), choices=SHOW_OPTION_CHOICES, max_length=15)
    category = models.ManyToManyField(Category, verbose_name=_('Category'), related_name='property_names')

    # moderations
    order = models.PositiveIntegerField(_('Order'), default=1)
    is_published = models.BooleanField(_('is published'), default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Property name')
        verbose_name_plural = _('Property names')
        ordering = ('order', '-created_at',)

    def __str__(self):
        return self.title


class PropertyValue(models.Model):
    title = models.CharField(_('Title'), max_length=40)
    property_name = models.ForeignKey(PropertyName, verbose_name=_('Property Name'), on_delete=models.CASCADE, related_name='property_values')

    # moderations
    order = models.PositiveIntegerField(_('Order'), default=1)
    is_published = models.BooleanField(_('is published'), default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Property Value')
        verbose_name_plural = _('Property Values')
        ordering = ('order', '-created_at',)

    def __str__(self):
        return self.title


class ProductProperties(models.Model):
    product = models.ForeignKey(Product, verbose_name=_('Product'), on_delete=models.CASCADE, related_name='product_properties',)
    property_value = models.ForeignKey(PropertyValue, verbose_name=_('Property Value'), on_delete=models.CASCADE, related_name='product_properties',)
    in_stock = models.BooleanField(_('In Stock'), default=True)

    # moderators
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Product Properties')
        verbose_name_plural = _('Product Properties')
    
    def __str__(self):
        return f"Product: {self.product}, Property: {self.property_value}"

class ProductDiscount(models.Model):
    CHOICES_DISCOUNT = (
        (1, _('Faiz')),
        (2, _('Manat')),
    )
    products = models.ManyToManyField(Product, verbose_name=_('Product Discounts'), related_name='product_discounts',)
    compaign = models.CharField(_('Compaign'), max_length=120)
    discount_type = models.IntegerField(_('Discount Type'),choices=CHOICES_DISCOUNT)
    discount_amount = models.DecimalField(_('Discount Amount'),max_digits=7, decimal_places=2)
    deadline = models.DateTimeField(_('Deadline'),)
    is_active = models.BooleanField(_('Is Active'), default=True)

    # moderators
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Product Discount')
        verbose_name_plural = _('Product Discounties')
    
    def __str__(self):
        return f"Compaign: {self.compaign}, Discount Amount: {self.discount_amount}"

class Bonuse(models.Model):
    title = models.CharField(_('Title'), max_length=20)
    image = models.FileField(upload_to='bonuse')
    description = models.TextField(_('Description'))
    bonuse = models.IntegerField(_('Bonuse'), default=5)

    # moderators
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Bonuse')
        verbose_name_plural = _('Bonuses')
        ordering = ('created_at',)

    def __str__(self):
        return self.title

core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django import forms

# class OrderForm(ModelForm):
#     class Meta:
#         model=Order
#         fields='__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','last_name','email','phone_number','password1','password2']

core/views.py
from django.views.generic import ListView, TemplateView

from django.shortcuts import render,redirect
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout
from django.contrib.auth.decorators import login_required   

from core.models import Bonuse
from core.models import Product
from core.models import ProductImage



# def index(request):
#     return render(request,'index.html')

def product(request):
    return render(request,'product.html')



def logoutUser(request):
    logout(request)
    return redirect('login')
@login_required(login_url='login')

def basket(request):
    return render(request ,'basket.html')

def checkout(request):
    return render(request ,'checkout.html')

def sign_up(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form=CreateUserForm()

        if request.method=='POST':
            form=CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user=form.cleaned_data.get('username')
                messages.success(request,'Account was created for' + user)
                return redirect('login')



        context={'form':form}
        return render(request ,'sign_up.html',context)

def login(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method=='POST':
            print(request.POST)
            username=request.POST.get('username')
            password=request.POST.get('password')
            user=authenticate(request,username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return redirect('home')
            else:
                messages.info(request,'Email or password is incorrect')


        return render(request,'login.html')

# def bonuses(request):
#     return render(request, 'membership_card.html')


class BonuseListView(ListView):
    model = Bonuse
    template_name = 'membership_card.html'

class IndexTemplateView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['product_list'] = Product.objects.all()[:8]
        return context

core/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="az" class="no-js">

<head>
    <title>Cinici.az</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="description" content=" " />
    <meta name="viewport" content="width=device-width" />
    <link rel="apple-touch-icon" sizes="180x180" href="media/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="media/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="media/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/slick.css' %}" type="text/css" />
    <link rel="stylesheet" href="{%static 'css/slick-theme.css' %}" type="text/css" />
    <link rel="stylesheet" href="{%static 'css/style.css' %}" type="text/css" />
    <link rel="stylesheet" href="{%static 'css/login.css' %}" type="text/css" />
    <link rel="stylesheet" href="{%static 'css/responsive.css' %}" type="text/css" />
     <link rel="stylesheet" href="{%static 'css/basket.css' %}" type="text/css" />
      <link rel="stylesheet" href="{%static 'css/checkout.css' %}" type="text/css" />
       <link rel="stylesheet" href="{%static 'css/sign_up.css' %}" type="text/css" />
    {% block css %}
    {% endblock %}
    
<body id="default" class="default">
    <div class="container-base">

        {% include 'includes/navbar.html' %}

        {% block content %}
        {% endblock %}

        {% include 'includes/footer.html' %}

    </div>
    <div id="snackbar"></div>
    <!-- jQuery -->
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/static/oscar/js/jquery/jquery.min.js"><\/script>')</script>
    
    <!-- Twitter Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Oscar -->
    <script src="{% static 'js/ui.js' %}"></script>
    
    <!-- injector:js -->
    <script src="{% static 'js/slick.js'%}"></script>
    <script src="{% static 'js/slider.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    <script src="{% static 'js/price_range_script.js' %}"></script>
    <script src="{% static 'js/popup.js'%}"></script>
    {% block js %}
    {% endblock %}
</body>
    
    </html>

core/templates/basket.html
{% extends  'base.html' %}

{% load static %}

{% block content %}
    
<div class="add-white-space"></div>
            <section id="basket-section">
                  <p style="display:none" id="line_delete_confirm_message"> Sebetden bu mehsulu silmekde eminsinizmi</p>
                <div class="container">
                    
                    <div class="mini-title">
                        <p>Səbətinizdəki məhsullar (1)</p>
                    </div>
                    <form action="." method="post" class="basket_summary" id="basket_formset">
                    <input type='hidden' name='csrfmiddlewaretoken' value='XYNPnFzEqU7He6XNp0mYHPjh0rr5VGuMBxtjhShrb5dAZpO3O44n7JD2uQ8GDCLs' />
                    <input type="hidden" name="form-TOTAL_FORMS" value="1" id="id_form-TOTAL_FORMS" /><input type="hidden" name="form-INITIAL_FORMS" value="1" id="id_form-INITIAL_FORMS" /><input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS" /><input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS" />
                    <div class="main-basket">


                        
                        <div class="left-sect">
                            
                            
                            <div class="basket-card">
                                <div class="card-left">
                                    
                                    
                                        <a href="/catalogue/-/038_10819/"><img class="thumbnail" src="{%static 'images/8c9b802122a6ed4284c1fc028a980bb3.jpg'%}" alt="image"/></a>
                                    
                                    
                                </div>
                                <div class="card-right">
                                    <div class="content">
                                        <input type="hidden" name="form-0-id" value="2020" id="id_form-0-id" />
                                        <a href="/catalogue/-/038_10819/"><p class="drk">Fever Qadın Ətək </p></a>
                                            
                                                
                                                <p class="content-p-item">Kod: 84727</p>
                                                
                                            
                                        <div class="about">
                                            
                                                <p class="content-p-item">Rəng: Yasil</p>
                                                <p class="content-p-item">Ölçü: 038</p>
                                            
                                        </div>
                                        <div class="count">
                                            <span>Ədəd:</span>
                                            <div class="inputGroupCount">
                                                <input type="number" class="number-select" value="1" disabled>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="price">
                                        <div class="price-top">
                                            
                                                <span class="discount"><s>95,00 ₼</s></span>
                                                <span>66,50 ₼</span>
                                            
                                        </div>
                                        <div class="price-bottom">
                                            <a href="" style="display: none;">Düzəliş et</a>
                                            <a href="/basket/line/2020/remove/" class="delete-basket-button"
                                                                data-delete="id_form-0-DELETE"
                                                                data-id="0"
                                                                data-behaviours="remove">Sil</a>
                                            <div style="display:none">
                                                <input type="checkbox" name="form-0-save_for_later" id="id_form-0-save_for_later" />
                                                <input type="checkbox" name="form-0-DELETE" id="id_form-0-DELETE" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            
                        </div>
                        
                        <div class="right-sect">
                            




                            <div class="right-top">
                                <div class="line">
                                    <p>Məhsullar (1)</p>
                                    <span>95,00 ₼</span>
                                </div>
                                <div class="line line-item">
                                    <p class="basket-discount">Endirim</p>
                                        <span class="align-right">-28,50 ₼</span>
                                </div>
                                <div class="line line-item">
                                    <p>Çatdırılma</p>
                                    <span>
                                        
                                            0,00 ₼
                                        
                                    </span>
                                </div>
                                <p>50 ₼-dən yuxarı alış-verişlərdə çatdırılma pulsuz!</p>
                            </div>
                            <div class="right-bottom">
                                <div class="line">
                                    <p>CƏMİ</p>
                                    <span>66,50 ₼ </span>
                                </div>
                                <button type="button" class="button-green submit-payment">Sifarişə davam et</button>
                            </div>
                        </div>
                    </div>                   
                    </form>
                </div>
            </section>
            
  
 {%endblock%}

core/templates/checkout.html
{% extends  'base.html' %}

{% load static %}

{% block content %}
<div class="add-white-space"></div>
<section id="proceed-to-payment">
    <div class="container">
        <form class="wrapper" action="/checkout/shipping-address/" method="post" id="new_shipping_address" onsubmit="return formValid();">
            <input type='hidden' name='csrfmiddlewaretoken' value='c0vEBxkyUK2O3gomvcVYN6CSgaxbocmUQzb8vK2lFV8HOzfCUgDnd0WDKzeM68DA' />
            <div class="col-left">
                    <div class="personal-info-box">
                    <h4 class="title">Şəxsi Məlumatlar</h4>
                    <div class="form-wrapper">
                            <div class="input-wrapper">
                                <label for="">Ad *</label>
                                <input type="text" name="first_name" class="required " maxlength="255" id="id_first_name" />
                            </div>
                            <div class="input-wrapper">
                                <label for="">Soyad *</label>
                                 <input type="text" name="last_name" class="required " maxlength="255" id="id_last_name" />
                            </div>
                            <div class="input-wrapper">
                                <label for="phone-no">Telefon *</label>

                                <div class="inputHolder">
                                    <span>+994</span>
                                    <input class="required" type="text" name="phone_number" id="phone-no" placeholder="(50) 123-45-67">
                                </div>
                            </div>
                            <div class="input-wrapper">
                                <label for="">ÇİNİCİ müştəri kodu (əgər varsa)</label>
                                <input type="text" name="user_ID" id="customer-code" placeholder="0000  0000  0000  0000">
                            </div>
                        <div class="input-wrapper hide-select">
                            <label for="">Şəhər * </label>
                            <div class="select-item"><select name="line1" maxlength="255" id="id_line1" class="s-hidden">
                                <option value="Baku">Bakı</option>
                                <option value="Xirdalan">Xırdalan</option>

            </select><div class="styledSelect">Bakı</div><ul style="display: none;"><li rel="Baku">Bakı</li><li rel="Xirdalan">Xırdalan</li></ul></div>
                        </div>
                        <div class="input-wrapper">
                            <label for="">Çatdırılacaq ünvan * </label>
                            <input type="text" name="line2" class="required " placeholder="Nərimanov ray., Ə. Əliyev küçəsi" maxlength="255" id="id_line2" />
                        </div>
                        </div>

                        <div class="input-wrapper">
                            <label for="">Qeyd</label>
                            <textarea name="notes" cols="30" rows="4" id="id_notes"></textarea>
                        </div>

                </div>
                </div>
            <div class="col-right">
                <div class="submit-order">
                    <ul class="prod-info">
                        <li>
                            <p>Məhsullar (1)</p>
                            <p>95,00 ₼</p>
                        </li>
                        <li>
                            <p>Endirim</p>
                            <p>-28,50 ₼</p>
                        </li>
                        <li>
                            <p>Çatdırılma</p>
                            <p>0,00 ₼</p>
                        </li>
                        <span>50 ₼-dən yuxarı alış-verişlərdə çatdırılma pulsuz!</span>
                    </ul>
                    <div class="title">
                        <h4>Cəmi</h4>
                        <span>66,50 ₼</span>
                    </div>
                    <p style="display:none" id="service_terms_error_nofication"> Xidmət şərtləri ile razılaşın</p>
                    <div class="checkbox-wrapper">
                        <input type="checkbox" id="approve" required="required">
                        <label for="approve"><a href="" data-toggle="modal" data-target="#service-terms">Xidmət şərtlərini</a> oxudum və qəbul edirəm</label>
                    </div>
                    <button type="button" class="button-green submit-payment">Sifarişə davam et</button>
                </div>

                <div class="order-info">
                 
                    <span>Sifarişləriniz 1-3 gün ərzində çatdırılır.</span>
                </div>
            </div>
        </form>
    </div>
</section>

        </div>
    </div>
 {%endblock%}

core/templates/favourite.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="favourites.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="reset.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
</head>

<body>
        <div class="section">
        <div class="container">
            <div class="row">
              <div class="col col-lg-3 col-md-3 col-sm-12 col-xs-12" id="leftside" >
                    <p>Xoş gəlmisiniz</p>
                    <h2>Tural Safarli</h2>
                    <ul class="filter">
                        <li><a href="">Sifarişlərim <img src="/static/arrow right.png" alt=""></a></li>
                        <li><a href="">Bonuslar <img src="/static/arrow right.png" alt=""></a></li>
                        <li><a  href="">Tənzimləmələr <img src="/static/arrow right.png" alt=""></a></li>
                        <li><a class="selected"  href="">Bəyənilənlər <img src="/static/arrow right.png" alt=""></a></li>
                        <li><a href="">Şifrəni dəyiş <img src="/static/arrow right.png" alt=""></a></li>
                        <li><a href="">Çıxış <img src="/static/arrow right.png" alt=""></a></li>
                    </ul>

                 
                  

              </div>
              <div class="col col-lg-9 col-md-9 col-sm-12 col-xs-12" id="rightside">
                  <p>Bəyənilənlər</p>
                  <div class="wishlist">
                    <label for="">Sırala</label>
                    <select name="favourite" required="" id="id_favourite">
                      <option value="" selected="">Ən yenilər</option>
                    
                      <option value="1">Qiymət (Artan)</option>
                    
                      <option value="2">Qiymət (Azalan)</option>
                    
                    </select>
                    <input type="checkbox" name="" id="favcheck">
                    <span>Tükənən məhsulları göstərmə</span>
                  </div>
                  <div class="wishlist_row">
                    <p>Bəyənilənlər siyahınızda məhsul tapılmadı.</p>
                  </div>
                      
                 
               

              </div>

            </div>
        </div>
    </div>
           

    

 
</body>

</html>

core/templates/membership_card.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

  
  
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->

  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/membership_card.css' %}">

{% endblock %}

      {% block content %}
      <div class="container">
      <div class="row">
        <div class="col-md-12 head">
          <h1>ÜZVLÜK KARTLARI</h1>
          <p></p>

        </div>
        <div class="col-md-12 menu">
          <div class="menutabs">
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12" style="padding-left: 10px; padding-right: 10px;">
                <div class="owl-carousel owl-theme">
                  {% for bonuse in bonuse_list %}
                  <div class="item {% if forloop.counter is 1 %} cart-active {% endif %}" data-show-item="#show-item-{{bonuse.id}}">
                    <div class="card_des">
                      <a href="#" class="active">
                        <div class="cardimg1" style="background-image: url('{{ bonuse.image.url}}');"></div>
                        <p>{{bonuse.title}}</p>
                      </a>
                    </div>
                  </div>
                  {% endfor %}
                 
                </div>
              </div>
            </div>
          </div>
          <section class="menuwrapper">
            {% for bonuse in object_list %}
            <article id="show-item-{{bonuse.id}}" class="menu_item {% if forloop.counter == 1 %} item_active {% endif %}">
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 info">
                  <div class="col-md-4 col-sm-4">
                    <div class="card_image">
                      <img src="{{bonuse.image.url}}" alt="">
                    </div>
                  </div>
                  <div class="col-md-8 col-sm-8 col-xs-12 more_info">
                    <h3>{{bonuse.title|upper}} CART</h3>
                    <p>{{bonuse.description}}</p>
                    <a href="">Bonus: {{bonuse.bonuse}}%</a>
                  </div>

                </div>
              </div>

            </article>
            {% endfor %}
          </section>
        </div>
        <div class="graybox">
          <h1>HƏDİYYƏ KARTLARI</h1>
          <div class="d-flex">
            <div class="left col-md-4 col-sm-5 col-xs-12">
              <img src="{% static '/images/cl_H0p73dF_f7Dt4U2.png' %}" alt="">
            </div>
            <div class="center col-md-5 col-sm-4 col-xs-12">
              <div class="graybox_text_holder">
                Sevdiklərini Çinici

                <br>
                <span>
                    HƏDİYYƏ KARTI

                </span><br>
                ilə sevindir!
                Daha çox al!
              </div>


            </div>
            <div class="right11 col-sm-3 col-xs-12">
              <a href="">Ətraflı</a>
            </div>
          </div>
        </div>
      </div>
    </div>
      {% endblock %}


{% block js %}
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/membership_card.js' %}"></script>
{% endblock %}
</body>

</html>